// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh8YcY74xXNMCg4hEckfsMlUVQ-7_yDCA',
    appId: '1:296037056963:web:a6dc07a740299e6ed2bd76',
    messagingSenderId: '296037056963',
    projectId: 'study-buddy-58b99',
    authDomain: 'study-buddy-58b99.firebaseapp.com',
    storageBucket: 'study-buddy-58b99.appspot.com',
    measurementId: 'G-HEJBEKRBSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbROYqdRJOnjis5nCQaZPh5NJlrDLTGNU',
    appId: '1:296037056963:android:ca4d28f19c1ce086d2bd76',
    messagingSenderId: '296037056963',
    projectId: 'study-buddy-58b99',
    storageBucket: 'study-buddy-58b99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ZsuwuvZB8j-cWoadmMy6d2FOgWAi9jg',
    appId: '1:296037056963:ios:eb06e822a063fdc9d2bd76',
    messagingSenderId: '296037056963',
    projectId: 'study-buddy-58b99',
    storageBucket: 'study-buddy-58b99.appspot.com',
    iosBundleId: 'com.example.studyBuddy',
  );
}
